### ISSUE TITLE
Installing gem issues

### ISSUE THREAD

**Issue by nellshamrell** [newcontext/kitchen-terraform#10]
Hello!

For some reason attempting to install this gem using bundle install is not working for me when using bundler 1.12.5
```
$ bundle --trust-profile HighSecurity
Unknown switches '--trust-profile
```
However, this command does:

```
$ gem install kitchen-terraform -P HighSecurity
Successfully installed kitchen-terraform-0.1.0
```
Should the Readme be updated to use this version of installing the gem?

Thanks!

**Comment by ncs-alane** [comment]
Hi @nellshamrell; thanks for the report!

`--trust-profile` is definitely a typo; it is supposed to read `--trust-policy`. :blush: The argument is equivalent to `gem install <...> -P/--trust-profile` but I recommend using bundler to simplify the management of dependencies. @nictrix has submitted #12 to correct the README so we will have this fix shipped shortly.

**Comment by ncs-alane** [comment]
0.1.1 has been released, which includes a patch to fix this documentation issue.
