### ISSUE TITLE
Unable to load Terraform driver

### ISSUE THREAD

**Issue by nellshamrell** [newcontext/kitchen-terraform#11]
Hello!

I am currently using Ruby 2.3.1 with rvm.  I installed the kitchen-terraform gem like this:

```
$ gem install kitchen-terraform --trust-profile HighSecurity
```

I have set up my .kitchen.yml like so:

```
---
driver:
  name: terraform

provisioner:
  name: terraform
  variable_files:
    - variables.tf

transport:
  name: ssh

verifier:
  name: terraform

platforms:
  - name: ubuntu

suites:
  - name: example
```

However, when I run $ kitchen list, I get this error:

```
$ kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'terraform' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
```

Anyone else seen this issue?

**Comment by nellshamrell** [comment]
More info:

I am using test kitchen 1.10.2 installed through the ChefDK.  The ruby version ChefDK uses is 2.1.8.

I used rvm to use Ruby 2.3.1.  I also installed test kitchen again under 2.3.1 and I installed kitchen-terraform under 2.3.1 as well.  But I am still seeing the same error.

**Comment by nellshamrell** [comment]
UPDATE!
I was able to work around this by adding a Gemfile to my terraform config and adding test-kitchen and kitchen-terraform to it, then running $bundle exec kitchen list

**Comment by matt-mcc1** [comment]
hey @nellshamrell - would you mind explaining how you did this? I'm facing the same issue and wish to follow your fix

**Comment by aaron-lane** [comment]
Hey @matt-mcc1! Please follow the [Installation Instructions](https://github.com/newcontext-oss/kitchen-terraform#kitchen-terraform-ruby-gem).

**Comment by shyambandi** [comment]
Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'terraform' driver from the load path. Did you mean: azurerm, digitalocean, dokken, dummy, ec2, exec, gce, hyperv, openstack, proxy, ssh_base, vagrant, vcenter, vra ? Please ensure that your driver is installed as a gem or included in your Gemfile if using 
Bundler.

Can some one help me with this?

**Comment by aaron-lane** [comment]
Hi @shyambandi! Please follow the [Installation Instructions](https://github.com/newcontext-oss/kitchen-terraform#kitchen-terraform-ruby-gem).

**Comment by shyambandi** [comment]
> Hi @shyambandi! Please follow the [Installation Instructions](https://github.com/newcontext-oss/kitchen-terraform#kitchen-terraform-ruby-gem).

I followed steps to create Gemfile and then bundle install, no luck. Still seeing the same error

**Comment by aaron-lane** [comment]
@shyambandi please open a new issue and provide details to reproduce the problem 🙏🏼
