### ISSUE TITLE
Support Terraform 0.7

### ISSUE THREAD

**Issue by ncs-alane** [newcontext/kitchen-terraform#17]
https://www.terraform.io/upgrade-guides/0-7.html

**Comment by shakatechdayne** [comment]
When do you think support will be added? I am really loving kitchen-terraform however some of the modules I am developing require TF 0.7

**Comment by ncs-alane** [comment]
I'm working on simplifying the internals of the project for the 0.2 release which will hopefully allow me to introduce backward compatible support for Terraform 0.7 in the 0.3 release. 0.2 should be out by the end of the week; 0.3 should be a week or two after that.

**Comment by SydOps** [comment]
any updates, my environment has been upgraded to terraform 0.7 already, wait for the support in kitchen-terraform.

Thanks.

**Comment by ncs-alane** [comment]
@SydOps kitchen-terraform 0.2 should be released later today. I've already started implementing support for Terraform 0.7 in the ncs-alane-0.3.0 branch and I hope to be able to release it by the end of the week.
