### ISSUE TITLE
More robust state parsing

### ISSUE THREAD

**Issue by jbussdieker** [newcontext/kitchen-terraform#25]
It would useful to be able to access values that exist in the terraform.tfstate file that can't be output in the test fixtures. My initial thoughts were to expose the state using something like [Hashie](https://github.com/intridea/hashie) and leave schema details up to the test writer which will make supporting future Terraform versions less painful.

**Comment by ncs-alane** [comment]
This may be better implemented as a separate gem. I'm concerned because this would introduce a feature that could not be guaranteed to be backward compatible.
