### ISSUE TITLE
Add a retry option to converge and destroy steps

### ISSUE THREAD

**Issue by esword** [newcontext/kitchen-terraform#36]
We often have problems with terraform failing due to erroneous AWS API errors.  For example, a TF script may create a VPC, internet gateway, and route table.  It will create the first two and then attempt to create the last using the id of the gateway and get an "InvalidInternetGatewayID.NotFound" trying to create the route table.  If you then rerun terraform, it will work fine.  This is not a big deal to work around when running commands manually, but it's a pain when running on a CI system because it will tear down the whole infrastructure if you are using the "kitchen test" command or running a script that always calls kitchen destroy at the end.

Idea is to add in an option for the provisioner that would retry the apply X number of times (in Provisioner.apply_execution_plan or wrapping that with another method).

**Comment by nictrix** [comment]
I've worked around this problem before by using a null resource that forces a wait on the resource that takes awhile to come up.

It's definitely a hack using that or doing multiple applies. But atleast with the null resource you would use the same code that ran in CI that runs in production.

**Comment by ncs-alane** [comment]
I agree that this sounds like an issue better handled by the Terraform configuration.

**Comment by ncs-alane** [comment]
@esword is that solution acceptable?

**Comment by ncs-alane** [comment]
@esword is that solution acceptable?

**Comment by esword** [comment]
Yes, the null resource work around fixed the issue I had.  Thanks for the suggestion. Problems with the AWS API still come up at random points and cause erroneous failures, but hopefully this is something TF itself can work out.

**Comment by nictrix** [comment]
Great to hear it worked for you. I do agree TF should figure out how to do retries when APIs error out on it.
