### ISSUE TITLE
Auto-create output directory for tfplan and tfstate 

### ISSUE THREAD

**Issue by esword** [newcontext/kitchen-terraform#39]
if you just run with a .kitchen directory, it will fail on converge with something like
```Error writing plan file: open /my/project/dir/.kitchen/kitchen-terraform/default-ubuntu/terraform.tfplan: no such file or directory```

Must create both kitchen-terraform and default-ubuntu manually before it will run.

**Comment by ncs-alane** [comment]
Were the contents of `.kitchen/` manually altered? I just tested the example project with no `.kitchen/` and it worked as expected.

**Comment by esword** [comment]
I have done it with both my active project and then a very trimmed down testing scope.  The one significant difference may be that I am running TF 0.7.3, so I have to tweak the version check in the provisioner before I run:

```sed -i 's/v0.6/v'$TERRAFORM_VERSION'/' "/usr/local/bundle/bundler/gems/kitchen-terraform-02568555e0a1/lib/kitchen/provisioner/terraform.rb"
```
Are you creating the directories, or are you expecting TF to do it?  Maybe it's behavior changed.

Here's the simple example.
[module_exp.zip](https://github.com/newcontext/kitchen-terraform/files/477262/module_exp.zip)

**Comment by ncs-alane** [comment]
Okay, it should be easy to ensure the directory is created.
