### ISSUE TITLE
Don't call destroy if no state file

### ISSUE THREAD

**Issue by esword** [newcontext/kitchen-terraform#40]
Terraform currently has a [bug](https://github.com/hashicorp/terraform/issues/8918) if you do this.  So you cannot call "kitchen test" because it attempts to call destroy first and will error.  Pending TF fixing the issue (and as a general performance improvement), perhaps add in a `provisioner.is_destroy_required` call and call that in `Driver.destroy` before calling `plan_destructive_execution` and `apply_execution_plan`.  The `is_destroy_required` call would check if there is a state file and (ideally) if it has any resources.  (The bug occurs even if there is a statefile, but all resources have been removed.)  The second part isn't strictly necessary because can work around it outside of kitchen by manually removing state file after previous destroy calls.

**Comment by ncs-alane** [comment]
Do you have an example repository with kitchen-terraform configured? I'm not able to recreate this issue with the [detailed example](../examples) project on the [0.3.0 branch](../tree/ncs-alane-0.3.0). Granted, I have the feature to ensure the state and plan parent directories exist implemented locally, but this issue doesn't seem related.

**Comment by esword** [comment]
It happens with this little mini-project using TF 0.7.3.
[Uploading module_exp.zip…]()

**Comment by nictrix** [comment]
@ncs-alane if you run the Dockerfile @esword provided in #43 , it appears to error out in the latest branch, I had to add this before the kitchen run: `mkdir -p .kitchen/kitchen-terraform/example-ubuntu`

**Comment by ncs-alane** [comment]
@nictrix that's related to #39.
