### ISSUE TITLE
Non-module test harness resources?

### ISSUE THREAD

**Issue by dustyburwell** [newcontext/kitchen-terraform#49]
I'd love to have a way to define resources that are only used during testing.

The module I'm building is only responsible for laying down some basic networking infrastructure. Later modules will reference the state output by this one and add other infrastructure as well as instances. Is there a way that I can define additional resources, instances etc, that are only used during testing? This could also be useful for poking holes for SSHing in through restrictive network ACLs for testing purposes. Also, a module that is adding onto existing infrastructure might need some additional bits to be added before the module scripts are run. For instance, in a hub and spokes network design, I'd like to create the hub as a part of the test harness for testing a spoke module.

For the last example, my current approach is to assume the hub exists and pass in references to it with variables, but this might not always be a tenable solution.

Any thoughts?

**Comment by dustyburwell** [comment]
Hmm... I must have missed this [fixtures directory](https://github.com/newcontext/kitchen-terraform/tree/master/examples/detailed/test/fixtures) in the example before. This may be what I'm missing here.

**Comment by ncs-alane** [comment]
Thanks for your interest in the project!

You can use the [provisioner's directory configuration option](https://github.com/newcontext/kitchen-terraform#directory) to change the pathname of the Terraform configuration that is being tested. This means you can create a test module that uses your production module and then run tests against the instances in the test module.

Once #7 is implemented, which I suspect will introduce support for testing the APIs of any Terraform provider, this strategy will no longer be required.

**Comment by dustyburwell** [comment]
Awesome. Thanks for the quick response.
