### ISSUE TITLE
inspec & ssh question

### ISSUE THREAD

**Issue by pantocrator27** [newcontext/kitchen-terraform#54]
I am a noob with respect to inspec so I apologize in advance.  It seems like kitchen-terraform works well when you are provisioning EC2 infrastructure that you can login to and perform your tests.  Let's say I wanted to use Terraform to provision just a security group or SNS topic.  Is there a way I can tell inspec to not SSH into the infrastructure to test but just test from my host.  I know if I was using inspec natively I could achieve this.

**Comment by ncs-alane** [comment]
Hi @pantocrator27:

Thanks for your interest in the project! 

What you're describing will be possible with the implementation of #7, which I'm hoping will be included in the next release.
